// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: urls.sql

package database

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO
  urls (id, short_url, default_url)
VALUES
  (gen_random_uuid (), $1, $2)
RETURNING
  id, short_url, default_url
`

type CreateUrlParams struct {
	ShortUrl   string
	DefaultUrl string
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl, arg.ShortUrl, arg.DefaultUrl)
	var i Url
	err := row.Scan(&i.ID, &i.ShortUrl, &i.DefaultUrl)
	return i, err
}
